# Random seed for reproducibility
seed: 42

# Model name â€” used to load the right dataset files
model_type: carreau_yasuda

# Model architecture: for scalar output, last layer = 1
model:
  layers: [256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 1]  # 10 hidden layers, output=1
  dropout: 0.1
  activation: relu

# Training hyperparameters
training:
  num_epochs: 500
  batch_size: 128
  learning_rate: 1e-2
  patience: 50  # Early stopping patience
  lambda_phys: 1  # << NEW physics loss weight (only used in PINN script)
  use_physics: true         # <<< Switch to false for pure data mode
  weight_decay: 1e-4
  constant_frac: 0.8
  
# Directory where checkpoints and plots will be saved
output_dir: ./trained_models/carreau_yasuda

device: gpu                 # Informative; JAX uses jax.device_count()
check_val_every_n_epoch: 3  # Match PyTorch validation frequency