# ===========================
# Global settings
# ===========================
seed: 42
model_type: maxwell_B

# New solver parameters
eta0: 25        # zero-shear viscosity for Maxwell-B
lam: 10         # relaxation time for Maxwell-B

data:
  balanced_split: true     # true or false
  scaling_mode: standard   # "minmax" or "standard"
# ===========================
# Model architecture
# ===========================
model:
  layers: [9, 256, 256, 256, 6]   # Last layer will be set to 6 automatically
  dropout: 0                   # Dropout rate
  activation: tanh                # relu, tanh, sigmoid

# ===========================
# Training hyperparameters
# ===========================
training:
  # List of λ_phys values for sweep mode
  # PINN mode when λ_phys > 0, pure data mode when λ_phys = 0
  lambda_phys: [0.3]

# Total epochs
  num_epochs: 500

  # Batch size
  batch_size: 64

  # Initial learning rate for AdamW
  learning_rate: 1e-4

  # L2 weight decay for AdamW
  weight_decay: 1e-4


# ===========================
# Output directory
# ===========================
output_dir: ./trained_models/maxwell_B