seed: 42
model_type: maxwell_B

data:
  balanced_split: true
  scaling_mode: dimensionless   # <<< NEW MODE

model:
  layers: [9, 256, 256, 256, 256, 6]
  dropout: 0.0                   # disable dropout for regression
  activation: tanh

training:
  lambda_phys: [0.3]
  num_epochs: 500
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 1e-4

output_dir: ./trained_models/maxwell_B_dimless